# Database instance
services:
  mssql:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: data-warehouse
    volumes:
      - events_mssql:/var/opt/mssql
      - ./setup.sql:/usr/config/setup.sql
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Passw@rd
      - MSSQL_PID=Developer
      - MSSQL_DB=events_service
      - MSSQL_USER=SA
      - MSSQL_PASSWORD=Passw@rd
      - MSSQL_DB_AUDIT_LOG=events_service_audit_log
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  events_mssql:
